version: '3.4'

services:
  apigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44388
      - ASPNETCORE_Kestrel__Certificates__Development__Password="f2c262c9-8945-4e8a-bc4c-f32f1cfa14d8"
    ports:
      - "3965:80"
      - "44388:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3964:80"

  blog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3959:80"

  fileupload:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3975:80"